# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    image: mariadb
    # restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dbroot
    volumes:
      - ./docker-data/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - mariadb:db
    
